import type { Metadata } from "next";
import "./globals.css";
import IframeHeightManager from "../components/IframeHeightManager";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="antialiased pt-12 pb-20">
                {children}
                <IframeHeightManager />
            </body>
        </html>
    );
}
